# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - strapi

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- script: |
    git remote add heroku https://heroku:$(heroku_pat)@git.heroku.com/brunstadtv-newsfeed.git
    git subtree push --prefix strapi heroku master
  displayName: 'Heroku'
